<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Social Network Login</title>
	    <style>
	      body {font-family: 'Lucida Grande', Verdana, Arial, sans-serif;}
	      h1 a {text-decoration: none; color: #3b5998;}
	      h1 a:hover {text-decoration: underline;}
	    </style>
	</head>
	<body>
		<?=$this->content()?>
	</body>
</html>