
	<div id='content'>
		<div class='container'>
			<div class='inner_container content_container'>
				<div class='page_content'>
					

<h1>Privacy Policy</h1>
<p><b>fusPic* respects your privacy.</b></p>
<p>Any personal information you provide to us including and similar to your name, address, telephone number and e-mail address will not be released, sold, or rented to any entities or individuals outside of fusPic*.</p>

<p><b>Credit card details</b></p>
<p>fusPic* will never ask for Credit Card details and request that you do not enter it on any of the forms on fusPic*.</p>

<p><b>External Sites.</b></p>
<p>fusPic* is not responsible for the content of external internet sites. You are advised to read the privacy policy of external sites before disclosing any personal information.</p>

<p><b>Cookies </b></p>
<p>A "cookie" is a small data text file that is placed in your browser and allows fusPic* to recognize you each time you visit this site(customisation etc). Cookies themselves do not contain any personal information, and fusPic* does not use cookies to collect personal information. Cookies may also be used by 3rd party content providers such as newsfeeds.</p>

<p><b>Remember The Risks Whenever You Use The Internet </b></p>
<p>While we do our best to protect your personal information, we cannot guarantee the security of any information that you transmit to fusPic* and you are solely responsible for maintaining the secrecy of any passwords or other account information. In addition other Internet sites or services that may be accessible through fusPic* have separate data and privacy practices independent of us, and therefore we disclaim any responsibility or liability for their policies or actions. </p>
<p>Please contact those vendors and others directly if you have any questions about their privacy policies.</p>

For any other information email <a href='mailto:info@fuspic.com'>webmaster</a>





				</div>
			</div>
		</div>
	</div>
