<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link href="/core/css/upload-tool.css" media="screen, projection" rel="stylesheet" type="text/css" />
		<title>Fuspic Uploader</title>
	</head>
	<body>
		<div class='inner_container content_container content-page'>
			<div class='page_content'>
				<p>We are really sorry, <strong>"<?=$this['error']['msg']?>"</strong> error occured. 
					<a href="javascript:history.back()">Click Here</a> to go back, or contact
						<a href="/about/contact">FUSPIC</a> regarding this issue</p>
			
			<? if ( $this['isDebug']): ?>
				<pre>
					<?var_dump($this)?>
				</pre>
			<? endif;?>
			</div>
		</div>
	</body>
</html>