<?if($this->user):?>
<ul>
	<li>
		<a href="/u/<?=$this->user['username'] /*@TODO Fix CrossSiteScript attack here*/?>">
			<img class="pull_left" src="<?= $this->user['profile_image'] ?>" width="20px" />
			<span id="topbar_username_loggedin" class="pull_left">
				<?=$this->user['username']?>
			</span>
			<div class='clear'></div>
		</a>
		<div id='topbar_login_dropdown' class='topbar_dropdown'>
			<ul>
				<li>
					<a href="/user/logout">Sign out</a>
				</li>
			</ul>
		</div>
</ul>
<?else:?>
<ul>
	<li>
		<a id='topbar_register' href='#'>Register</a>
		<div id='topbar_register_dropdown' class='topbar_dropdown'>
			<?=$this->action('registerform', 'user')?>
		</div>
	</li>
	<li>
		<a id='topbar_login' href='#'>Sign In</a>
		<div id='topbar_login_dropdown' class='topbar_dropdown'>
			<?=$this->action('loginform', 'user')?>
			<!-- <a href='/' class='pull_left green'>Forgot Password?</a> -->
			<!-- <a class='action_btn pull_right' href=''>SIGN IN</a> -->
			<!-- <div class='clear'></div> -->
		</div>
	</li>
</ul>
<?endif;?>
