<div id='content'>
	<div class='container'>
		<div class='inner_container '>
			<div id="user_single_container">
				 <div id="user_single_image" class="pull_left content_container" style="width:20%">
					<img src="<?= $this->cred['profile_image'] ?>" width="100%" />
				</div>
				<div id='user_single_info' class="pull_right content_container" style="width:73%">
					<div id="profile_edit_box">
						edit profile
					</div>
					<div class="profile_editable">
						<h2><?= $this->cred['username'] ?></h2>
					</div>
				</div>
			</div>
			<!--<pre><? var_dump($this->cred) ?></pre>-->
			
		</div>
	</div>
</div>