<form id="lostpassform" name="lostpass" action="/user/lostpass" method="post" class="form-stacked">
	<fieldset>
		<div class="clearfix">
			<div class="input">
				<label for="email">Email</label>
				<input type="text" name="email">
			</div>
		</div>
		<div class="actions">
			<button type="submit" class="btn primary">
				<span>RETRIEVE</span>
			</button>
		</div>
		<div class="clearfix">
			<div class="alert-message block-message error fade in" data-alert="alert" style="display:none;"></div>
		</div>
	</fieldset>
</form>