<form id="registerform" name="register" action="/user/register" method="post" >
	<div class='form_block'>
		<label for='email'>Email</label>
		<input type='text' name='email' />
	</div>
	<div class='form_block'>
		<label for='password'>Password</label>
		<input type='password' name='password' />
	</div>
	<div class='form_block'>
		<label for='repeatpassword'>Verify Password</label>
		<input type='password' name='repeatpassword' />
	</div>
	<button type="submit" class='action_btn pull_right'>
		<span>REGISTER</span>
	</button>
	<div class='clear'></div>
</form>