<?if($this->isPost && !$this->error):?>
	<h2>Your password has been reset.</h2>
	<h3>You are now being redirected to the <a href="/">Home Page</a></h3>
	<script type="text/javascript">setTimeout("location.href = '/';",5000);</script>
<?else:?>
	<form id="resettpassform" name="lostpass" action="/user/resetpass" method="post" class="form-stacked">
		<h2>Two steps away from your new password!</h2>
		<fieldset>
			<div class="clearfix">
				<div class="input">
					<label for="password">Your new password:</label>
					<input type="password" name="password">
				</div>
				<div class="input" style="margin-top:20px;">
					<label for="verify_password">Verify new password:</label>
					<input type="password" name="verify_password">
				</div>
				<div><input type="hidden" name="token" value="<?=$this->token?>" /></div>
				<div><input type="hidden" name="email" value="<?=$this->email?>" /></div>
			</div>
			<?if($this->isPost && $this->error):?>
				<div style="color:red;margin-left:2px;"><?=$this->error?></div>
			<?endif;?>
			<div class="actions" style="background:none;border:none;margin-top:0px;margin-left:-18px;">
				<button type="submit" class="btn primary">
					<span>SUBMIT</span>
				</button>
			</div>
			<div class="clearfix">
				<div class="alert-message block-message error fade in" data-alert="alert" style="display:none;"></div>
			</div>
		</fieldset>
	</form>
<?endif;?>