		<div id="root-footer"></div>
	</div>
	<footer>
		
	</footer>

  
	<script src="/_assets/js/vendor/jquery.js"></script>

	<script src="/_assets/js/foundation/foundation.js"></script>
	<script src="/_assets/js/foundation/foundation.alerts.js"></script>
	<script src="/_assets/js/foundation/foundation.clearing.js"></script>
	<script src="/_assets/js/foundation/foundation.cookie.js"></script>
	<script src="/_assets/js/foundation/foundation.dropdown.js"></script>
	<script src="/_assets/js/foundation/foundation.forms.js"></script>
	<script src="/_assets/js/foundation/foundation.joyride.js"></script>
	<script src="/_assets/js/foundation/foundation.magellan.js"></script>
	<script src="/_assets/js/foundation/foundation.orbit.js"></script>
	<script src="/_assets/js/foundation/foundation.placeholder.js"></script>
	<script src="/_assets/js/foundation/foundation.reveal.js"></script>
	<script src="/_assets/js/foundation/foundation.section.js"></script>
	<script src="/_assets/js/foundation/foundation.tooltips.js"></script>
	<script src="/_assets/js/foundation/foundation.topbar.js"></script>
	
  
	<script>
		$(document).foundation();
	</script>
</body>
</html>
